apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    framework: nestjs
    app: {{ .Values.deployment.name }}
    name: {{ .Values.deployment.name }}
  name: {{ .Values.deployment.name }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      framework: nestjs
      app: {{ .Values.deployment.name }}
      name: {{ .Values.deployment.name }}
  template:
    metadata:
      labels:
        framework: nestjs
        app: {{ .Values.deployment.name }}
        name: {{ .Values.deployment.name }}
      {{- if .Values.deployment.annotations }}
      annotations:
        {{- toYaml .Values.deployment.annotations | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ .Values.deployment.name }}
      {{- if and (.Values.deployment.affinity) (ge .Values.deployment.replicas 2.0) }}
      affinity: {{- toYaml .Values.deployment.affinity | nindent 8 }}
      {{- end }}

      containers:
        - name: {{ .Values.deployment.name }}
          image: {{ .Values.container.image.registry }}/{{ .Values.container.image.repository }}:{{ .Values.container.image.tag }}
          imagePullPolicy: {{ .Values.container.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.deployment.containerPort.number }}
              protocol: {{ .Values.deployment.containerPort.protocol }}
          {{- if .Values.container.resources }}
          resources: {{- toYaml .Values.container.resources | nindent 12 }}
          {{- end }}
          readinessProbe:
            httpGet:
              path: {{ .Values.deployment.readinessProbe.endpoint }}
              port: {{ .Values.deployment.containerPort.number }}
            successThreshold: {{ .Values.deployment.readinessProbe.successThreshold }}
            failureThreshold: {{ .Values.deployment.readinessProbe.failureThreshold }}
            periodSeconds: {{ .Values.deployment.readinessProbe.periodSeconds }}
            initialDelaySeconds: {{ .Values.deployment.readinessProbe.initialDelaySeconds }}
          livenessProbe:
            httpGet:
              path: {{ .Values.deployment.livenessProbe.endpoint }}
              port: {{ .Values.deployment.containerPort.number }}
            successThreshold: {{ .Values.deployment.livenessProbe.successThreshold }}
            failureThreshold: {{ .Values.deployment.livenessProbe.failureThreshold }}
            periodSeconds: {{ .Values.deployment.livenessProbe.periodSeconds }}
            initialDelaySeconds: {{ .Values.deployment.livenessProbe.initialDelaySeconds }}
          env:
            - name: K8S_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: K8S_DEPLOYMENT_NAME
              value: {{ .Values.deployment.name }}
            - name: K8S_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: K8S_RESTART_DELAY_MS
              value: "30000"
          {{- if .Values.container.additionalVariables }}
          {{- toYaml .Values.container.additionalVariables | nindent 12 }}
          {{- end }}
      imagePullSecrets:
        - name: {{ .Values.container.image.pullSecrets }}